### ISSUE TITLE
(Deconvolve EDA) Error when Nan at start of data

### ISSUE THREAD

**Issue by WBoode** [BredaUniversityResearch/ExperienceLabPipeline#4]
The following error appears if there is a NaN value at the start of the array / input data (conductance)

Array indices must be positive integers or logical values.
 
Error in deconvolve_eda (line 91)

                data.conductance(starttime-1:endtime+1)   = data.conductance(endtime+1);

**Comment by HRevers** [comment]
Solved. 23/01/2024
